ctor: dlpf.agents.our_dqn.ConvAndDensePointwiseAgent
kwargs:
  hidden_sizes:
    - 50
    - 50
    - 50
  hidden_activations:
    - tanh
    - tanh
    - tanh
  hidden_dropouts: []
  hidden_batchnorm:
    - True
    - True
    - True
  conv_cores:
    - 32
  conv_core_sizes:
    - 3
  conv_strides:
    - 1
  conv_activations:
    - sigmoid
  conv_dropouts: []
  conv_pooling:
    - None
  conv_batchnorm:
    - True
  output_activation: sigmoid
  action_policy: identity
  batch_size: 64
  epoch_number: 100
  loss: mae
  max_memory_size: 40
  optimizer: {ctor: adadelta}
  passes_over_train_data: 50
  validation_part: 0.1
  keras_verbose: 2
  early_stopping_patience: 3
  train_gen_processes_number: 1
  train_gen_queue_size: 100
  reduce_lr_on_plateau_factor: 0.2
  reduce_lr_on_plateau_patience: 100000
  train_data_output_type: free_hinge
  weighting_function: linear
