ctor: dlpf.agents.our_dqn.TwoLayerAgent
kwargs:
  action_policy: {ctor: epsilon_greedy, eps: 0.1}
  batch_size: 64
  epoch_number: 20
  hidden_activation: relu
  hidden_size: 16
  loss: mean_squared_error
  max_memory_size: 250
  optimizer: {ctor: rmsprop, lr: 0.01}
  passes_over_train_data: 10
  validation_part: 0.1
