ctor: dlpf.agents.our_dqn.TwoLayerAgent
kwargs:
  action_policy: {ctor: annealed_epsilon_greedy, decrease_coef: 0.99, eps: 0.05}
  batch_size: 64
  epoch_number: 20
  hidden_activation: relu
  hidden_size: 128
  loss: mean_squared_error
  max_memory_size: 250
  optimizer: {ctor: adam, lr: 0.01}
  passes_over_train_data: 10
  validation_part: 0.1
