ctor: dlpf.agents.our_dqn.ConvAndDenseAgent
kwargs:
  hidden_sizes:
    - 100
    - 100
  hidden_activations:
    - relu
    - relu
  hidden_dropouts:
    - 0.2
    - 0.2
  conv_cores:
    - 16
    - 16
  conv_core_sizes:
    - 32
    - 32
    - 32
  conv_strides:
    - 2
    - 2
    - 2
  conv_activations:
    - relu
    - relu
    - relu
  conv_dropouts:
    - 0.2
    - 0.2
    - 0.2
  conv_pooling:
    - max
    - max
    - max
  output_activation: softmax
  action_policy: {ctor: annealed_epsilon_greedy, eps: 0.9, final_eps: 0.1, episodes_number: 5000, degree: 2}
  batch_size: 64
  epoch_number: 100
  loss: binary_crossentropy
  max_memory_size: 40
  optimizer: {ctor: adadelta}
  passes_over_train_data: 100
  validation_part: 0.1
  keras_verbose: 2
  early_stopping_patience: 2
  train_gen_processes_number: 1
  train_gen_queue_size: 100
  reduce_lr_on_plateau_factor: 0.2
  reduce_lr_on_plateau_patience: 100000
  train_data_output_type: softmax
