ctor: dlpf.agents.our_dqn.OneLayerAgent
kwargs:
  action_policy: {ctor: annealed_epsilon_greedy, eps: 0.9, final_eps: 0.01, episodes_number: 5000, degree: 2}
  batch_size: 32
  epoch_number: 100
  loss: squared_hinge
  output_activation: tanh
  max_memory_size: 250
  optimizer: rmsprop
  passes_over_train_data: 2
  validation_part: 0.1
  keras_verbose: 2
  early_stopping_patience: 1
  train_gen_processes_number: 1
  train_gen_queue_size: 100
  train_data_output_type: free_hinge
