ctor: dlpf.agents.our_dqn.ConvAndDenseAgent
kwargs:
  hidden_sizes:
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
  hidden_activations:
    - relu
    - relu
    - relu
    - relu
    - relu
    - relu
    - relu
    - relu
    - relu
    - relu
  hidden_dropouts: []
  hidden_batchnorm:
    - True
    - True
    - True
    - True
    - True
    - True
    - True
    - True
    - True
    - True
  conv_cores: []
  conv_core_sizes: []
  conv_strides: []
  conv_activations: []
  conv_dropouts: []
  conv_pooling: []
  conv_batchnorm: []
  output_activation: tanh
  action_policy: {ctor: annealed_epsilon_greedy, eps: 0.9, final_eps: 0.1, degree: 2}
  batch_size: 64
  epoch_number: 100
  loss: squared_hinge
  max_memory_size: 250
  optimizer: {ctor: adadelta}
  passes_over_train_data: 10
  validation_part: 0.1
  keras_verbose: 2
  early_stopping_patience: 3
  train_gen_processes_number: 1
  train_gen_queue_size: 100
  reduce_lr_on_plateau_factor: 0.2
  reduce_lr_on_plateau_patience: 100000
  train_data_output_type: tanh_hinge
