ctor: PathFindingByPixelWithDistanceMapEnv-v1
kwargs:
  done_reward: 10
  local_goal_reward: 5
  target_on_border_reward: 5
  obstacle_punishment: 0
  greedy_distance_reward_weight: 0
  absolute_distance_reward_weight: 0
  absolute_distance_observation_weight: 0.1
  map_shape: !!python/tuple [20, 20]
  tasks_dir: data/20x20/imported/paths
  maps_dir: data/20x20/imported/maps
  path_policy: random_start_and_finish_straight
  stop_game_after_invalid_action: false
  task_policy: sequential
  vision_range: 20

