ctor: PathFindingByPixelWithDistanceMapEnv-v1
kwargs:
  done_reward: 10
  local_goal_reward: 5
  map_shape: !!python/tuple [501, 501]
  maps_dir: data/current/imported/maps
  obstacle_punishment: 1
  path_policy: go_straight
  stop_game_after_invalid_action: false
  target_on_border_reward: 5
  task_policy: sequential
  vision_range: 10
