ctor: PathFindingByPixelWithDistanceMapEnv-v1
kwargs:
  done_reward: 10
  local_goal_reward: 5
  map_shape: !!python/tuple [512, 512]
  tasks_dir: data/rooms_full/imported/paths
  maps_dir: data/rooms_full/imported/maps
  obstacle_punishment: 4
  path_policy: random_start_and_finish_straight
  stop_game_after_invalid_action: false
  target_on_border_reward: 5
  task_policy: sequential
  vision_range: 10
  greedy_distance_reward_weight: 0.1
  absolute_distance_reward_weight: 0.1
  absolute_distance_observation_weight: 0.1
