ctor: dlpf.agents.our_dqn.TwoLayerAgent
kwargs:
  hidden_size: 50
  hidden_activation: relu
  dropout: 0.2
  action_policy: {ctor: annealed_epsilon_greedy, eps: 0.9, final_eps: 0.1, episodes_number: 5000, degree: 2}
  batch_size: 64
  epoch_number: 20
  loss: hinge
  max_memory_size: 250
  optimizer: {ctor: rmsprop, lr: 0.03}
  passes_over_train_data: 10
  validation_part: 0.1
  keras_verbose: 2
  early_stopping_patience: 2
  train_gen_processes_number: 1
  train_gen_queue_size: 100
