ctor: dlpf.agents.our_dqn.TwoLayerAgent
kwargs:
  hidden_size: 20
  hidden_activation: relu
  dropout: 0.8
  action_policy: {ctor: annealed_epsilon_greedy, eps: 0.4, decrease_coef: 0.99}
  batch_size: 64
  epoch_number: 20
  loss: mean_squared_error
  max_memory_size: 250
  optimizer: {ctor: rmsprop, lr: 0.01}
  passes_over_train_data: 10
  validation_part: 0.1
