ctor: dlpf.agents.our_dqn.OneLayerAgent
kwargs:
  action_policy: {ctor: epsilon_greedy}
  batch_size: 4
  epoch_number: 100
  loss: mean_squared_error
  max_memory_size: 250
  optimizer: {ctor: rmsprop, lr: 0.01}
  passes_over_train_data: 10
  validation_part: 0.1
